name: NER Implementation Repo
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ner_test_env
          environment-file: environment.yml
          condarc-file: environment.yml
          auto-activate-base: false
      - name: Test with pytest
        run: pytest -vv tests/test_env_vars.py
